# Week 1
### Info
```
Name : Shreyas Nayak
240911006
Dataset : netflix_sample_500.csv
TDA DAV/ML domain
```

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("netflix_sample_500.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         500 non-null    object
 1   director      336 non-null    object
 2   cast          459 non-null    object
 3   country       454 non-null    object
 4   date_added    500 non-null    object
 5   release_year  500 non-null    int64
 6   duration      500 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.5+ KB

## Question 1
#### How many rows and columns are there in the dataset?

In [7]:
print("no of rows : " , df.shape[0])
print("no of columns : " , df.shape[1])

no of rows :  500
no of columns :  7

## Question 2
#### Print the names of all the columns.

In [11]:
print("names of columns : ")
display(df.columns)

names of columns :

Index(['title', 'director', 'cast', 'country', 'date_added', 'release_year',
       'duration'],
      dtype='object')

## Question 3
#### Display the first 5 and last 3 rows of the dataset.

In [14]:
print("first 5 data :")
display(df.head())
print("last 3 data :")
df.tail(3)

first 5 data :

,title,director,cast,country,date_added,release_year,duration
0,"Game Over, Man!",Kyle Newacheck,"Adam DeVine, Anders Holm, Blake Anderson, Utka...",United States,"March 23, 2018",2018,102 min
1,Arsenio Hall: Smart & Classy,Brian Volk-Weiss,Arsenio Hall,United States,"October 29, 2019",2019,63 min
2,Kazoops!,NaN,"Reece Pockney, Scott Langley, Alex Babic, Gemm...",Australia,"May 5, 2017",2017,3 Seasons
3,We Are the Champions,NaN,NaN,United States,"November 17, 2020",2020,1 Season
4,"Pablo Escobar, el patrón del mal",NaN,"Andrés Parra, Angie Cepeda, Cecilia Navia, Vic...",Colombia,"February 3, 2021",2012,1 Season

last 3 data :

,title,director,cast,country,date_added,release_year,duration
497,Korean Cold Noodle Rhapsody,NaN,Paik Jong-won,NaN,"August 20, 2021",2021,1 Season
498,Look for a Star,Andrew Lau Wai-Keung,"Andy Lau, Qi Shu, Zhang Hanyu, Denise Ho, Domi...",Hong Kong,"December 1, 2018",2009,117 min
499,40 Sticks,Victor Gatonye,"Robert Agengo, Mwaura Bilal, Andreo Kamau, Caj...",Kenya,"November 20, 2020",2019,93 min

## Question 4
#### Select and display only the title and release_year columns.

In [18]:
df[["title", "release_year"]].head(15)

                               title  release_year
0                    Game Over, Man!          2018
1       Arsenio Hall: Smart & Classy          2019
2                           Kazoops!          2017
3               We Are the Champions          2020
4   Pablo Escobar, el patrón del mal          2012
5       Saint Seiya: The Lost Canvas          2009
6                              Fauda          2020
7               The Cook of Castamar          2021
8       The App That Stole Christmas          2020
9                               Mute          2018
10                       Drugs, Inc.          2015
11                    Den of Thieves          2018
12            The President's Barber          2004
13                          The Dirt          2019
14                    Brews Brothers          2020

## Question 5
#### Using iloc, show rows 10 to 20 (inclusive).

In [21]:
df.iloc[10:21]

,title,director,cast,country,date_added,release_year,duration
10,"Drugs, Inc.",NaN,Mike Secher,United States,"March 23, 2019",2015,1 Season
11,Den of Thieves,Christian Gudegast,"Gerard Butler, Pablo Schreiber, O'Shea Jackson...",United States,"May 1, 2020",2018,140 min
12,The President's Barber,Chan-sang Lim,"Kang-ho Song, So-ri Moon, Jae-eung Lee, Yeong-...",South Korea,"October 1, 2017",2004,116 min
13,The Dirt,Jeff Tremaine,"Douglas Booth, Iwan Rheon, Colson Baker, Danie...",United States,"March 22, 2019",2019,108 min
14,Brews Brothers,NaN,"Alan Aisenberg, Mike Castle, Carmen Flood, Mar...",United States,"April 10, 2020",2020,1 Season
15,Rodney Carrington: Here Comes the Truth,Brandon Jones,Rodney Carrington,United States,"October 3, 2017",2017,66 min
16,Planet Hulk,Sam Liu,"Rick D. Wasserman, Lisa Ann Beley, Mark Hildre...",United States,"June 1, 2020",2010,81 min
17,Tree Man,"Jon Reiner, Brad Rothschild",NaN,Canada,"November 1, 2016",2015,82 min
18,Ladies First,Uraaz Bahl,NaN,India,"March 8, 2018",2018,40 min
19,King Jack,Felix Thompson,"Charlie Plummer, Cory Nichols, Christian Madse...",United States,"July 1, 2016",2015,81 min
20,"I love you, stupid",Laura Mañá,"Quim Gutiérrez, Natalia Tena, Alfonso Bassave,...",Spain,"May 15, 2020",2019,88 min

## Question 6
#### Check for missing values in each column.

In [23]:
df.isnull().sum()

title             0
director        164
cast             41
country          46
date_added        0
release_year      0
duration          0
dtype: int64

## Question 7
#### Fill missing values in the country column with "Unknown" and in the director column with "Not Available"

In [30]:
df["country"].fillna("Unknown",inplace = True)
df["director"].fillna("Not Available" , inplace = True)
df.isnull().sum()

title            0
director         0
cast            41
country          0
date_added       0
release_year     0
duration         0
dtype: int64

## Question 8
#### Replace "United States" with "USA" in the country column.

In [31]:
df["country"] = df["country"].replace("United States", "USA")
df.head()

,title,director,cast,country,date_added,release_year,duration
0,"Game Over, Man!",Kyle Newacheck,"Adam DeVine, Anders Holm, Blake Anderson, Utka...",USA,"March 23, 2018",2018,102 min
1,Arsenio Hall: Smart & Classy,Brian Volk-Weiss,Arsenio Hall,USA,"October 29, 2019",2019,63 min
2,Kazoops!,Not Available,"Reece Pockney, Scott Langley, Alex Babic, Gemm...",Australia,"May 5, 2017",2017,3 Seasons
3,We Are the Champions,Not Available,NaN,USA,"November 17, 2020",2020,1 Season
4,"Pablo Escobar, el patrón del mal",Not Available,"Andrés Parra, Angie Cepeda, Cecilia Navia, Vic...",Colombia,"February 3, 2021",2012,1 Season

## Question 9
#### Create a new column content_type that contains "Movie" if duration contains "min" and "TV Show" if it contains "Season".

In [46]:
lis = []

for i in df["duration"]:
    if "min" in i :
        lis +=["Movie"]
    elif "Seasons" in i or "Season" in i :
        lis += ["TV Show"]


df["content_type"] = lis

df.head()

,title,director,cast,country,date_added,release_year,duration,content_type,years_since_release
0,"Game Over, Man!",Kyle Newacheck,"Adam DeVine, Anders Holm, Blake Anderson, Utka...",USA,"March 23, 2018",2018,102 min,Movie,7
1,Arsenio Hall: Smart & Classy,Brian Volk-Weiss,Arsenio Hall,USA,"October 29, 2019",2019,63 min,Movie,6
2,Kazoops!,Not Available,"Reece Pockney, Scott Langley, Alex Babic, Gemm...",Australia,"May 5, 2017",2017,3 Seasons,TV Show,8
3,We Are the Champions,Not Available,NaN,USA,"November 17, 2020",2020,1 Season,TV Show,5
4,"Pablo Escobar, el patrón del mal",Not Available,"Andrés Parra, Angie Cepeda, Cecilia Navia, Vic...",Colombia,"February 3, 2021",2012,1 Season,TV Show,13

## Question 10
#### Add a column years_since_release that shows how many years have passed since the release year (assuming current year is 2025).

In [47]:
lis2 = []

for i in df["release_year"] :
    lis2+= [(2025 - i)]

df["years_since_release"] = lis2

df.head()

,title,director,cast,country,date_added,release_year,duration,content_type,years_since_release
0,"Game Over, Man!",Kyle Newacheck,"Adam DeVine, Anders Holm, Blake Anderson, Utka...",USA,"March 23, 2018",2018,102 min,Movie,7
1,Arsenio Hall: Smart & Classy,Brian Volk-Weiss,Arsenio Hall,USA,"October 29, 2019",2019,63 min,Movie,6
2,Kazoops!,Not Available,"Reece Pockney, Scott Langley, Alex Babic, Gemm...",Australia,"May 5, 2017",2017,3 Seasons,TV Show,8
3,We Are the Champions,Not Available,NaN,USA,"November 17, 2020",2020,1 Season,TV Show,5
4,"Pablo Escobar, el patrón del mal",Not Available,"Andrés Parra, Angie Cepeda, Cecilia Navia, Vic...",Colombia,"February 3, 2021",2012,1 Season,TV Show,13

## Question 11
#### Group the dataset by release_year and count how many shows were released each year.

In [50]:
df[df["content_type"] == "TV Show"].groupby("release_year").size().sort_index(ascending=False)

release_year
2021    20
2020    24
2019    21
2018    24
2017    19
2016    14
2015    11
2014    10
2013     5
2012     4
2010     3
2009     4
2008     1
2007     1
2006     1
2004     1
2002     1
1998     1
1993     1
1963     1
dtype: int64

## Question 12
#### Find how many unique countries are represented in the dataset.

In [53]:
print("no of unique country : " , df["country"].nunique())

no of unique country :  99

# ThAnK YoU